# Generated by Django 3.0.10 on 2022-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=32)),
                ('population', models.IntegerField()),
                ('population_density', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gdp_per_capita', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
